# Generated by Django 4.1.5 on 2023-01-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
    ]
